spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ProductMicro?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

product:
  productCode: 9999
  productName: laptop
  category: electronics
  price: 112000
  status: true    
